# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glx_design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wspComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wspComboBox.sizePolicy().hasHeightForWidth())
        self.wspComboBox.setSizePolicy(sizePolicy)
        self.wspComboBox.setObjectName("wspComboBox")
        self.verticalLayout_3.addWidget(self.wspComboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.tagComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagComboBox.sizePolicy().hasHeightForWidth())
        self.tagComboBox.setSizePolicy(sizePolicy)
        self.tagComboBox.setObjectName("tagComboBox")
        self.horizontalLayout.addWidget(self.tagComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.ronlyCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ronlyCheckBox.setEnabled(False)
        self.ronlyCheckBox.setCheckable(True)
        self.ronlyCheckBox.setChecked(False)
        self.ronlyCheckBox.setObjectName("ronlyCheckBox")
        self.verticalLayout_3.addWidget(self.ronlyCheckBox)
        self.expTree = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expTree.sizePolicy().hasHeightForWidth())
        self.expTree.setSizePolicy(sizePolicy)
        self.expTree.setObjectName("expTree")
        self.expTree.headerItem().setText(0, "1")
        self.verticalLayout_3.addWidget(self.expTree)
        self.newExpButton = QtWidgets.QPushButton(self.centralwidget)
        self.newExpButton.setObjectName("newExpButton")
        self.verticalLayout_3.addWidget(self.newExpButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.overviewTab = QtWidgets.QWidget()
        self.overviewTab.setObjectName("overviewTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.overviewTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.overviewTab)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.titleEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.titleEdit.setObjectName("titleEdit")
        self.horizontalLayout_4.addWidget(self.titleEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.overviewTab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.tagsEdit = QtWidgets.QLineEdit(self.overviewTab)
        self.tagsEdit.setObjectName("tagsEdit")
        self.horizontalLayout_5.addWidget(self.tagsEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.createdLabel = QtWidgets.QLabel(self.overviewTab)
        self.createdLabel.setObjectName("createdLabel")
        self.horizontalLayout_7.addWidget(self.createdLabel)
        self.updatedLabel = QtWidgets.QLabel(self.overviewTab)
        self.updatedLabel.setObjectName("updatedLabel")
        self.horizontalLayout_7.addWidget(self.updatedLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.label_2 = QtWidgets.QLabel(self.overviewTab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.boldButton = QtWidgets.QPushButton(self.overviewTab)
        self.boldButton.setMaximumSize(QtCore.QSize(25, 25))
        self.boldButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldButton.setIcon(icon)
        self.boldButton.setCheckable(True)
        self.boldButton.setObjectName("boldButton")
        self.horizontalLayout_3.addWidget(self.boldButton)
        self.italicButton = QtWidgets.QPushButton(self.overviewTab)
        self.italicButton.setMaximumSize(QtCore.QSize(25, 25))
        self.italicButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/i.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicButton.setIcon(icon1)
        self.italicButton.setCheckable(True)
        self.italicButton.setObjectName("italicButton")
        self.horizontalLayout_3.addWidget(self.italicButton)
        self.underlineButton = QtWidgets.QPushButton(self.overviewTab)
        self.underlineButton.setMaximumSize(QtCore.QSize(25, 25))
        self.underlineButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/u.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlineButton.setIcon(icon2)
        self.underlineButton.setCheckable(True)
        self.underlineButton.setObjectName("underlineButton")
        self.horizontalLayout_3.addWidget(self.underlineButton)
        self.superscriptButton = QtWidgets.QPushButton(self.overviewTab)
        self.superscriptButton.setMaximumSize(QtCore.QSize(25, 25))
        self.superscriptButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/super.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.superscriptButton.setIcon(icon3)
        self.superscriptButton.setCheckable(True)
        self.superscriptButton.setObjectName("superscriptButton")
        self.horizontalLayout_3.addWidget(self.superscriptButton)
        self.subscriptButton = QtWidgets.QPushButton(self.overviewTab)
        self.subscriptButton.setMaximumSize(QtCore.QSize(25, 25))
        self.subscriptButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/sub.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subscriptButton.setIcon(icon4)
        self.subscriptButton.setCheckable(True)
        self.subscriptButton.setObjectName("subscriptButton")
        self.horizontalLayout_3.addWidget(self.subscriptButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.descriptionEdit = QtWidgets.QTextEdit(self.overviewTab)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout.addWidget(self.descriptionEdit)
        self.saveOverviewButton = QtWidgets.QPushButton(self.overviewTab)
        self.saveOverviewButton.setObjectName("saveOverviewButton")
        self.verticalLayout.addWidget(self.saveOverviewButton)
        self.tabWidget.addTab(self.overviewTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "glexsyn"))
        self.label_4.setText(_translate("MainWindow", "Tag:"))
        self.ronlyCheckBox.setText(_translate("MainWindow", "Read only workspace"))
        self.newExpButton.setText(_translate("MainWindow", "New experiment..."))
        self.label.setText(_translate("MainWindow", "Title:"))
        self.label_3.setText(_translate("MainWindow", "Tags:"))
        self.createdLabel.setText(_translate("MainWindow", "Created at:"))
        self.updatedLabel.setText(_translate("MainWindow", "Updated at:"))
        self.label_2.setText(_translate("MainWindow", "Description:"))
        self.saveOverviewButton.setText(_translate("MainWindow", "Save..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overviewTab), _translate("MainWindow", "Overview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Notes"))

